# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'byt8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for byt8
  # add the Firebase pod for Google Analytics
  pod 'Firebase'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod ‘Firebase/Core’
  pod ‘Firebase/Database’
  pod ‘Firebase/Auth’

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods


end
